# Generated by Django 3.0.3 on 2020-02-23 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_auto_20200223_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='score',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='lecturecomment',
            name='star',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
